### ISSUE TITLE
CSS for replaced-content pseudo elements

### ISSUE THREAD

**Issue by jakearchibald** [WICG/shared-element-transitions#137]
Our pseudo elements `::page-transition-incoming-image(tag)` and `::page-transition-outgoing-image(tag)` are replaced content. But should that be represented somehow in the CSS we generate for the transition?

## Option 1 - a function

```css
::page-transition-outgoing-image(foo) {
  content: page-transition-outgoing-image(foo);
}

::page-transition-incoming-image(foo) {
  content: element(some-link-back-to-the-element);
}
```

`page-transition-outgoing-image(foo)` - this references the captured texture from the no-longer-existing element. Developers could take this function and use it on other elements, which raises questions around the lifetime of the image. Eg, does it become an invalid/empty image once the transition is complete?

`element(some-link-back-to-the-element)` - in this case we have something kinda like `element()` but not quite. We'd need to extend the API somehow so it behaves less like `element()` and more like we need it to for the page transition API (eg, not capturing the whole texture in some cases). This feels like a lot of work for little benefit.

## Option 1.5 - as above, but without extending `element()`

```css
::page-transition-incoming-image(foo) {
  content: page-transition-incoming-image(foo);
}
```

`page-transition-incoming-image(foo)` works similarly to `page-transition-outgoing-image(foo)` - it's specific to page transitions, and the link between `foo` and the actual texture is handled behind the scenes.

## Option 2 - a magic value

```css
::page-transition-outgoing-image(foo) {
  content: page-transition-image;
}

::page-transition-incoming-image(foo) {
  content: page-transition-image;
}
```

Here `page-transition-image` refers to the image associated with the pseudo element. Only the page transition system can set and unset this association. It's a little magic, but it explains how the element becomes replaced content, and doesn't have lifetime concerns.

## Option 3 - full magic

How the pseudo element becomes a replaced element is not defined in the CSS at all. This makes it similar in spirit to an `<img>`, which is also a replaced element without CSS defining the replacement.

With this option, we might be able to move to one of the other options later.
