### ISSUE TITLE
Can we have some good defaults for page-transition-tag

### ISSUE THREAD

**Issue by technikhil314** [WICG/shared-element-transitions#153]
Can we have attribute value of `id` or `data-testid` or `/^data-.*id$/` (if the attribute is present and if it has valid value on the element) as a default value for `page-transition-tag` which we can directly use in css rather than defining everytime we need to do custom transition on any element?

viz

in html
```html
<h1 id="title">Some title</h1>
```
and in css
```css
/* the title tag is automatically defined since id attribute has valid value of title on the html element */
::page-transition-container(title) {
   contain: paint
}
```
