### ISSUE TITLE
Define the base style that's inherited by the DOM elements created for transition

### ISSUE THREAD

**Issue by khushalsagar** [WICG/shared-element-transitions#94]
We need to clarify the parent element whose style is inherited by the DOM elements created for the transition. This would tie into #93 since by default the style would come from the originating element for the shadow DOM/pseudo element.

Another option is to not inherit any style from the ancestor, which is done for the backdrop pseudo element. This could impact whether CSS variables defined in the outer DOM (using :root) get applied when used with a selector for these transition elements. For example :

```css
:root {
  --transition-bg-color: brown;
}

*::transition::part(container) {
  background-color: var(--transition-bg-color);
}
```
